import type { Recommendation } from '@/components/RecommendationSection';

export const mockRecommendations: Recommendation[] = [
  {
    id: '1',
    title: 'The Last of Us',
    year: 2023,
    platform: 'HBO Max',
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop',
    rating: 8.9,
    confidence: 'Very High',
    genres: ['Action', 'Drama', 'Sci-Fi'],
    reasoning: 'Based on your preference for post-apocalyptic narratives and character-driven stories. The show has received critical acclaim (96% on Rotten Tomatoes) and matches your evening viewing mood. Similar to The Walking Dead which you rated highly.',
    reviews: [
      { source: 'IMDb', score: 8.9 },
      { source: 'RT', score: 9.6 },
    ],
    tags: ['🔥 Trending', '⭐ Critics\' Choice'],
    socialProof: '12 of your friends are watching',
  },
  {
    id: '2',
    title: 'Wednesday',
    year: 2022,
    platform: 'Netflix',
    poster: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop',
    rating: 8.2,
    confidence: 'Very High',
    genres: ['Comedy', 'Fantasy', 'Mystery'],
    reasoning: 'Your viewing history shows strong interest in dark comedy and supernatural themes. This Tim Burton series combines both elements with a fresh take on the Addams Family. Currently trending with 341.2M hours viewed in first month.',
    reviews: [
      { source: 'IMDb', score: 8.2 },
      { source: 'RT', score: 7.3 },
    ],
    tags: ['🔥 Trending'],
    socialProof: '8 of your friends are watching',
  },
  {
    id: '3',
    title: 'The Bear',
    year: 2023,
    platform: 'Disney+',
    poster: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=600&fit=crop',
    rating: 8.6,
    confidence: 'High',
    genres: ['Drama', 'Comedy'],
    reasoning: 'Matches your interest in character-driven dramas with fast-paced storytelling. The show\'s intense kitchen environment and personal growth themes align with your recent viewing of Succession. 23 Emmy nominations including Outstanding Drama Series.',
    reviews: [
      { source: 'IMDb', score: 8.6 },
      { source: 'Metacritic', score: 9.2 },
    ],
    tags: ['⭐ Critics\' Choice'],
    socialProof: '6 of your friends are watching',
  },
  {
    id: '4',
    title: 'Severance',
    year: 2022,
    platform: 'Apple TV+',
    poster: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&h=600&fit=crop',
    rating: 8.7,
    confidence: 'High',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    reasoning: 'Your high ratings for Black Mirror and Westworld suggest you enjoy thought-provoking sci-fi. This psychological thriller explores similar themes of identity and reality. Currently holds 97% on Rotten Tomatoes with universal critical acclaim.',
    reviews: [
      { source: 'IMDb', score: 8.7 },
      { source: 'RT', score: 9.7 },
    ],
    tags: ['⭐ Critics\' Choice'],
    socialProof: 'Won 2 Emmy Awards',
  },
  {
    id: '5',
    title: 'Succession',
    year: 2023,
    platform: 'HBO Max',
    poster: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=600&fit=crop',
    rating: 8.9,
    confidence: 'Very High',
    genres: ['Drama'],
    reasoning: 'Perfect match for your preference for prestige dramas with complex family dynamics. The show\'s sharp writing and stellar performances align with your viewing history. Final season won 6 Emmy Awards including Outstanding Drama Series.',
    reviews: [
      { source: 'IMDb', score: 8.9 },
      { source: 'Metacritic', score: 9.3 },
    ],
    tags: ['🔥 Trending', '⭐ Critics\' Choice'],
    socialProof: 'Won 19 Emmy Awards total',
  },
  {
    id: '6',
    title: 'The Night Agent',
    year: 2023,
    platform: 'Netflix',
    poster: 'https://images.unsplash.com/photo-1574267432644-f85fd0a82475?w=400&h=600&fit=crop',
    rating: 7.5,
    confidence: 'Medium',
    genres: ['Action', 'Thriller'],
    reasoning: 'Your watch history includes several political thrillers like Jack Ryan. This fast-paced series offers similar high-stakes action with conspiracy themes. Most-watched show on Netflix in Q1 2023 with 812M hours viewed.',
    reviews: [
      { source: 'IMDb', score: 7.5 },
      { source: 'RT', score: 7.8 },
    ],
    tags: ['🔥 Trending'],
    socialProof: '15 of your friends are watching',
  },
];

export const mockTrending: Recommendation[] = [
  {
    id: 't1',
    title: 'The Mandalorian',
    year: 2023,
    platform: 'Disney+',
    poster: 'https://images.unsplash.com/photo-1608889335941-32ac5f2041b9?w=400&h=600&fit=crop',
    rating: 8.7,
    confidence: 'High',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    reasoning: 'Trending globally with Season 3 release. Your Star Wars franchise interest and preference for action-adventure content make this a strong match.',
    reviews: [
      { source: 'IMDb', score: 8.7 },
      { source: 'RT', score: 9.3 },
    ],
    tags: ['🔥 Trending'],
    socialProof: '20 of your friends are watching',
  },
  {
    id: 't2',
    title: 'Poker Face',
    year: 2023,
    platform: 'Prime Video',
    poster: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=600&fit=crop',
    rating: 7.9,
    confidence: 'Medium',
    genres: ['Mystery', 'Drama'],
    reasoning: 'New mystery series from Knives Out creator Rian Johnson. Your enjoyment of procedural mysteries and character-driven narratives makes this a good fit.',
    reviews: [
      { source: 'IMDb', score: 7.9 },
      { source: 'RT', score: 9.9 },
    ],
    tags: ['🔥 Trending'],
    socialProof: 'From the creator of Knives Out',
  },
  {
    id: 't3',
    title: 'Beef',
    year: 2023,
    platform: 'Netflix',
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
    rating: 8.3,
    confidence: 'High',
    genres: ['Drama', 'Comedy', 'Thriller'],
    reasoning: 'Dark comedy exploring road rage aftermath. Matches your preference for character-driven dramas with unconventional premises. Won 8 Emmy Awards including Outstanding Limited Series.',
    reviews: [
      { source: 'IMDb', score: 8.3 },
      { source: 'RT', score: 9.8 },
    ],
    tags: ['🔥 Trending', '⭐ Critics\' Choice'],
    socialProof: 'Won 8 Emmy Awards',
  },
  {
    id: 't4',
    title: 'Silo',
    year: 2023,
    platform: 'Apple TV+',
    poster: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=600&fit=crop',
    rating: 8.1,
    confidence: 'High',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    reasoning: 'Post-apocalyptic mystery series matching your preference for dystopian narratives. Similar themes to The Last of Us but with a unique underground society premise.',
    reviews: [
      { source: 'IMDb', score: 8.1 },
      { source: 'RT', score: 8.8 },
    ],
    tags: ['🔥 Trending'],
    socialProof: 'Renewed for Season 2',
  },
  {
    id: 't5',
    title: 'The Diplomat',
    year: 2023,
    platform: 'Netflix',
    poster: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=400&h=600&fit=crop',
    rating: 7.8,
    confidence: 'Medium',
    genres: ['Drama', 'Thriller'],
    reasoning: 'Political thriller starring Keri Russell. Your interest in geopolitical dramas and smart dialogue-driven shows makes this a solid recommendation.',
    reviews: [
      { source: 'IMDb', score: 7.8 },
      { source: 'RT', score: 8.4 },
    ],
    tags: ['🔥 Trending'],
    socialProof: '9 of your friends are watching',
  },
  {
    id: 't6',
    title: 'Daisy Jones & The Six',
    year: 2023,
    platform: 'Prime Video',
    poster: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=600&fit=crop',
    rating: 7.9,
    confidence: 'Medium',
    genres: ['Drama', 'Music'],
    reasoning: 'Based on the bestselling novel about a 1970s rock band. Your music documentary watch history and preference for period dramas suggest strong interest.',
    reviews: [
      { source: 'IMDb', score: 7.9 },
      { source: 'RT', score: 8.2 },
    ],
    socialProof: 'Based on bestselling novel',
  },
];
